### ISSUE TITLE
Il faut rapprocher les paquets de cartes du bouton « lancer de dé ». Celui de gauche (avec les écritures) est dans les dix dernières cartes gagnées.

### ISSUE THREAD

**Issue by callejonmelissa** [WildCodeSchool/2022-03-php-remote-1283-montbeliard-cite-libre#75]

**Comment by trueChoan** [comment]
rajoute aussi une phrase "niveau de la question" au dessus des dés du bas

**Comment by callejonmelissa** [comment]
@jfm-wcs Les changements s'appliquent seulement dans la console, impossible dans l'éditeur que ce soit en bootstrap ou en css
