### ISSUE TITLE
On ne comprend pas du tout les points gagnés grâce aux cartes liées. Elles sont toujours prises en compte ?

### ISSUE THREAD

**Issue by callejonmelissa** [WildCodeSchool/2022-03-php-remote-1283-montbeliard-cite-libre#79]

**Comment by trueChoan** [comment]
grosse issue bien chiante a gérer ça. 
peut etre ne pas mettre le recap des points gagnées ou perdu et juste afficher les cartes. Au moins ça le perturbera plus.
